In [340]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report, auc, roc_curve

In [341]:
df = pd.read_csv("D:\pyt\Assignment\Assignment 12- Naive Bayes\SalaryData_Train.csv")

In [342]:
df.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [343]:
df.shape

(30161, 14)

In [344]:
df.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [345]:
df.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [346]:
df.workclass.value_counts()

 Private             22285
 Self-emp-not-inc     2499
 Local-gov            2067
 State-gov            1279
 Self-emp-inc         1074
 Federal-gov           943
 Without-pay            14
Name: workclass, dtype: int64

In [347]:
df.education.value_counts()

 HS-grad         9840
 Some-college    6677
 Bachelors       5044
 Masters         1627
 Assoc-voc       1307
 11th            1048
 Assoc-acdm      1008
 10th             820
 7th-8th          557
 Prof-school      542
 9th              455
 12th             377
 Doctorate        375
 5th-6th          288
 1st-4th          151
 Preschool         45
Name: education, dtype: int64

In [348]:
df.maritalstatus.value_counts()

 Married-civ-spouse       14065
 Never-married             9725
 Divorced                  4214
 Separated                  939
 Widowed                    827
 Married-spouse-absent      370
 Married-AF-spouse           21
Name: maritalstatus, dtype: int64

In [349]:
df.occupation.value_counts()

 Prof-specialty       4038
 Craft-repair         4030
 Exec-managerial      3992
 Adm-clerical         3721
 Sales                3584
 Other-service        3212
 Machine-op-inspct    1965
 Transport-moving     1572
 Handlers-cleaners    1350
 Farming-fishing       989
 Tech-support          912
 Protective-serv       644
 Priv-house-serv       143
 Armed-Forces            9
Name: occupation, dtype: int64

In [350]:
df.relationship.value_counts()

 Husband           12463
 Not-in-family      7726
 Own-child          4466
 Unmarried          3212
 Wife               1406
 Other-relative      888
Name: relationship, dtype: int64

In [351]:
df.race.value_counts()

 White                 25932
 Black                  2817
 Asian-Pac-Islander      895
 Amer-Indian-Eskimo      286
 Other                   231
Name: race, dtype: int64

In [352]:
df.sex.value_counts()

 Male      20380
 Female     9781
Name: sex, dtype: int64

In [353]:
df.native.value_counts()

 United-States                 27504
 Mexico                          610
 Philippines                     188
 Germany                         128
 Puerto-Rico                     109
 Canada                          107
 India                           100
 El-Salvador                     100
 Cuba                             92
 England                          86
 Jamaica                          80
 South                            71
 China                            68
 Italy                            68
 Dominican-Republic               67
 Vietnam                          64
 Guatemala                        63
 Japan                            59
 Poland                           56
 Columbia                         56
 Iran                             42
 Haiti                            42
 Taiwan                           42
 Portugal                         34
 Nicaragua                        33
 Peru                             30
 Greece                           29
 

In [354]:
x_train= df.iloc[:, :13]
x_train 

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  
0                0            40   United-States  
1                0            13   United-States  
2                0            40   United-States  
3                0            40   United-States  
4                0            40            Cuba  
...            ...           ...             ...  
30156            0            38   United-States  
30157            0            40   United-States  
30158            0            40   United-States  
30159            0            20   United-States  
30160            0            40   United-States  

[30161 rows x 13 columns]

In [355]:
x_train= pd.get_dummies(x_train)
x_train.head()

age  educationno  capitalgain  capitalloss  hoursperweek  \
0   39           13         2174            0            40   
1   50           13            0            0            13   
2   38            9            0            0            40   
3   53            7            0            0            40   
4   28           13            0            0            40   

   workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                       0                     0                   0   
1                       0                     0                   0   
2                       0                     0                   1   
3                       0                     0                   1   
4                       0                     0                   1   

   workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  ...  \
0                        0                            0  ...   
1                        0                            1  ...   
2                        0                            0  ...   
3                        0                            0  ...   
4                        0                            0  ...   

   native_ Portugal  native_ Puerto-Rico  native_ Scotland  native_ South  \
0                 0                    0                 0              0   
1                 0                    0                 0              0   
2                 0                    0                 0              0   
3                 0                    0                 0              0   
4                 0                    0                 0              0   

   native_ Taiwan  native_ Thailand  native_ Trinadad&Tobago  \
0               0                 0                        0   
1               0                 0                        0   
2               0                 0                        0   
3               0                 0                        0   
4               0                 0                        0   

   native_ United-States  native_ Vietnam  native_ Yugoslavia  
0                      1                0                   0  
1                      1                0                   0  
2                      1                0                   0  
3                      1                0                   0  
4                      0                0                   0  

[5 rows x 102 columns]

In [356]:
y_train = df.iloc[:, -1]
y_train

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...  
30156     <=50K
30157      >50K
30158     <=50K
30159     <=50K
30160      >50K
Name: Salary, Length: 30161, dtype: object

In [357]:
df1 = pd.read_csv("D:\pyt\Assignment\Assignment 12- Naive Bayes\SalaryData_Test.csv")

In [358]:
x_test= df1.iloc[:, :13]
x_test

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  
0                0            0            40   United-States  
1                0            0            50   United-States  
2                0            0            40   United-States  
3             7688            0            40   United-States  
4                0            0            30   United-States  
...            ...          ...           ...             ...  
15055            0            0            40   United-States  
15056            0            0            36   United-States  
15057            0            0            50   United-States  
15058         5455            0            40   United-States  
15059            0            0            60   United-States  

[15060 rows x 13 columns]

In [359]:
x_test= pd.get_dummies(x_test)
x_test.head()

age  educationno  capitalgain  capitalloss  hoursperweek  \
0   25            7            0            0            40   
1   38            9            0            0            50   
2   28           12            0            0            40   
3   44           10         7688            0            40   
4   34            6            0            0            30   

   workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                       0                     0                   1   
1                       0                     0                   1   
2                       0                     1                   0   
3                       0                     0                   1   
4                       0                     0                   1   

   workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  ...  \
0                        0                            0  ...   
1                        0                            0  ...   
2                        0                            0  ...   
3                        0                            0  ...   
4                        0                            0  ...   

   native_ Portugal  native_ Puerto-Rico  native_ Scotland  native_ South  \
0                 0                    0                 0              0   
1                 0                    0                 0              0   
2                 0                    0                 0              0   
3                 0                    0                 0              0   
4                 0                    0                 0              0   

   native_ Taiwan  native_ Thailand  native_ Trinadad&Tobago  \
0               0                 0                        0   
1               0                 0                        0   
2               0                 0                        0   
3               0                 0                        0   
4               0                 0                        0   

   native_ United-States  native_ Vietnam  native_ Yugoslavia  
0                      1                0                   0  
1                      1                0                   0  
2                      1                0                   0  
3                      1                0                   0  
4                      1                0                   0  

[5 rows x 102 columns]

In [360]:
y_test = df1.iloc[:, -1]
y_test

0         <=50K
1         <=50K
2          >50K
3          >50K
4         <=50K
          ...  
15055     <=50K
15056     <=50K
15057     <=50K
15058     <=50K
15059      >50K
Name: Salary, Length: 15060, dtype: object

# Without using any scaling

In [361]:
gnb= GaussianNB()

In [362]:
gnb.fit(x_train,y_train)

GaussianNB()

In [363]:
y_pred = gnb.predict(x_test)

In [364]:
accuracy = np.round(accuracy_score(y_test, y_pred)*100, 2)
print(f"Accuracy of unscaled model is {accuracy} %")

Accuracy of unscaled model is 80.29 %


In [365]:
conf_mat= confusion_matrix(y_test, y_pred)
print(conf_mat)

[[9073 2287]
 [ 681 3019]]


# Using Minmaxscalar

In [366]:
from sklearn.preprocessing import MinMaxScaler

In [367]:
scaled= MinMaxScaler()

In [368]:
x_train_mm= scaled.fit_transform(x_train)
x_test_mm= scaled.transform(x_test)

In [369]:
x_train_mm

array([[0.30136986, 0.8       , 0.02174022, ..., 1.        , 0.        ,
        0.        ],
       [0.45205479, 0.8       , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.28767123, 0.53333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.56164384, 0.53333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.06849315, 0.53333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.47945205, 0.53333333, 0.1502415 , ..., 1.        , 0.        ,
        0.        ]])

In [370]:
x_test_mm

array([[0.10958904, 0.4       , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.28767123, 0.53333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.15068493, 0.73333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.28767123, 0.8       , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.36986301, 0.8       , 0.05455055, ..., 1.        , 0.        ,
        0.        ],
       [0.24657534, 0.8       , 0.        , ..., 1.        , 0.        ,
        0.        ]])

In [371]:
gnb_minmax= GaussianNB()

In [372]:
gnb_minmax.fit(x_train_mm, y_train)

GaussianNB()

In [373]:
y_pred_minmax = gnb_minmax.predict(x_test_mm)

In [374]:
from sklearn.metrics import accuracy_score

In [375]:
accuracy_minmax = np.round(accuracy_score(y_test, y_pred_minmax)*100,2)
print(f"Accuracy of MinMax scaled model is {accuracy_minmax} % ")

Accuracy of MinMax scaled model is 57.78 % 


In [376]:
conf_mat_minmax = confusion_matrix(y_test, y_pred_minmax)
print(conf_mat_minmax)

[[5265 6095]
 [ 264 3436]]


# Using RobustScalar

In [377]:
from sklearn.preprocessing import RobustScaler

In [378]:
robsc= RobustScaler()

In [379]:
x_train_rob = robsc.fit_transform(x_train)
x_test_rob = robsc.transform(x_test)

In [380]:
gnb_rob = GaussianNB()

In [381]:
gnb_rob.fit(x_train_rob, y_train)
y_pred_rob = gnb_rob.predict(x_test_rob)

In [382]:
accuracy_rob= np.round(accuracy_score(y_test, y_pred_rob)*100,2)
print(f"Accuracy of Robust scaled model is {accuracy_rob} % ")

Accuracy of Robust scaled model is 80.1 % 


In [383]:
conf_mat_rob = confusion_matrix(y_test, y_pred_rob)
print(conf_mat_rob)

[[9035 2325]
 [ 672 3028]]


# Using MaxAbsScalar

In [384]:
from sklearn.preprocessing import MaxAbsScaler

In [385]:
maxab= MaxAbsScaler()

In [386]:
x_train_maxab = maxab.fit_transform(x_train)
x_test_maxab = maxab.transform(x_test)

In [387]:
gnb_maxab = GaussianNB()

In [388]:
gnb_maxab.fit(x_train_maxab, y_train)

GaussianNB()

In [389]:
y_pred_maxab = gnb_maxab.predict(x_test_maxab)

In [390]:
accuracy_maxab = np.round(accuracy_score(y_test, y_pred_maxab)*100, 2)
print(f"Accuracy of MaxAbs scaled model is {accuracy_maxab} % ")

Accuracy of MaxAbs scaled model is 57.78 % 


In [391]:
conf_mat_maxabs = confusion_matrix (y_test,y_pred_maxab)
conf_mat_maxabs

array([[5265, 6095],
       [ 264, 3436]], dtype=int64)

# Using Standard Scalar 

In [392]:
from sklearn.preprocessing import StandardScaler

In [393]:
std = StandardScaler()

In [394]:
x_train_std = std.fit_transform(x_train)
x_test_std = std.transform(x_test)

In [395]:
gnb_std = GaussianNB()

In [396]:
gnb_std.fit(x_train_std, y_train)

GaussianNB()

In [397]:
y_pred_std = gnb_std.predict(x_test_std)

In [398]:
accuracy_std = np.round(accuracy_score(y_test, y_pred_std)*100,2)
print(f"Accuracy of standard scaled model is {accuracy_std} % ")

Accuracy of standard scaled model is 54.75 % 


In [399]:
conf_mat_std = confusion_matrix (y_test, y_pred_std)
print(conf_mat_std)

[[4775 6585]
 [ 230 3470]]


# Combing Results Together

In [400]:
results = pd.DataFrame({"Scaling_uesd":["unscaled", "MinmaxScalar", "RobustScalar", "MaxabsScalar", "StandardScalar"],
                       "Model_Accuracy": [accuracy,accuracy_minmax, accuracy_rob, accuracy_maxab, accuracy_std]})

In [401]:
results

Scaling_uesd  Model_Accuracy
0        unscaled           80.29
1    MinmaxScalar           57.78
2    RobustScalar           80.10
3    MaxabsScalar           57.78
4  StandardScalar           54.75

# Here it can be seen that  Unscaled data gives maximum accuracy score, followed by RobustScalar

In [402]:
print(f" Confusion Matrix for Unscaled data is \n {conf_mat}")

 Confusion Matrix for Unscaled data is 
 [[9073 2287]
 [ 681 3019]]


In [403]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       <=50K       0.93      0.80      0.86     11360
        >50K       0.57      0.82      0.67      3700

    accuracy                           0.80     15060
   macro avg       0.75      0.81      0.76     15060
weighted avg       0.84      0.80      0.81     15060



In [404]:
print(f" Confusion Matrix for Robust scaled data is \n {conf_mat_rob}")

 Confusion Matrix for Robust scaled data is 
 [[9035 2325]
 [ 672 3028]]


In [405]:
print(classification_report(y_test, y_pred_rob))

              precision    recall  f1-score   support

       <=50K       0.93      0.80      0.86     11360
        >50K       0.57      0.82      0.67      3700

    accuracy                           0.80     15060
   macro avg       0.75      0.81      0.76     15060
weighted avg       0.84      0.80      0.81     15060



In [430]:
y_test1= df["Salary"]
y_test1

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...  
30156     <=50K
30157      >50K
30158     <=50K
30159     <=50K
30160      >50K
Name: Salary, Length: 30161, dtype: object

In [431]:
y_test1= pd.DataFrame({"sal":y_test1 })
y_test1

sal
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
30156   <=50K
30157    >50K
30158   <=50K
30159   <=50K
30160    >50K

[30161 rows x 1 columns]

In [432]:
y_test1["sal"] =y_test1["sal"].map({"<=50K": "yes" , ">50K " : "no"})

In [433]:
y_test1

sal
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
30156  NaN
30157  NaN
30158  NaN
30159  NaN
30160  NaN

[30161 rows x 1 columns]

In [434]:
df.Salary.value_counts()

 <=50K    22653
 >50K      7508
Name: Salary, dtype: int64

In [454]:
from imblearn.over_sampling import RandomOverSampler, SMOTE

In [455]:
ros= RandomOverSampler()

In [456]:
x_resampled, y_resampled=ros.fit_resample(x_train, y_train)

In [457]:
y_resampled.value_counts()

 <=50K    22653
 >50K     22653
Name: Salary, dtype: int64

In [458]:
x_resampled

age  educationno  capitalgain  capitalloss  hoursperweek  \
0       39           13         2174            0            40   
1       50           13            0            0            13   
2       38            9            0            0            40   
3       53            7            0            0            40   
4       28           13            0            0            40   
...    ...          ...          ...          ...           ...   
45301   38           15            0            0            50   
45302   38           14            0            0            40   
45303   47           13            0            0            45   
45304   55           13            0            0            40   
45305   31           16            0         1977            99   

       workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                           0                     0                   0   
1                           0                     0                   0   
2                           0                     0                   1   
3                           0                     0                   1   
4                           0                     0                   1   
...                       ...                   ...                 ...   
45301                       0                     0                   1   
45302                       0                     0                   0   
45303                       0                     0                   1   
45304                       0                     0                   1   
45305                       0                     0                   1   

       workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  ...  \
0                            0                            0  ...   
1                            0                            1  ...   
2                            0                            0  ...   
3                            0                            0  ...   
4                            0                            0  ...   
...                        ...                          ...  ...   
45301                        0                            0  ...   
45302                        0                            1  ...   
45303                        0                            0  ...   
45304                        0                            0  ...   
45305                        0                            0  ...   

       native_ Portugal  native_ Puerto-Rico  native_ Scotland  native_ South  \
0                     0                    0                 0              0   
1                     0                    0                 0              0   
2                     0                    0                 0              0   
3                     0                    0                 0              0   
4                     0                    0                 0              0   
...                 ...                  ...               ...            ...   
45301                 0                    0                 0              0   
45302                 0                    0                 0              0   
45303                 0                    0                 0              0   
45304                 0                    0                 0              0   
45305                 0                    0                 0              0   

       native_ Taiwan  native_ Thailand  native_ Trinadad&Tobago  \
0                   0                 0                        0   
1                   0                 0                        0   
2                   0                 0                        0   
3                   0                 0                        0   
4                   0                 0                        0   
...               ...               ...                      ...   
45301               0              

In [459]:
gnb1= GaussianNB()

In [460]:
gnb1.fit(x_resampled, y_resampled )

GaussianNB()

In [461]:
y_predo = gnb1.predict(x_test)

In [463]:
print(classification_report(y_test, y_predo))

              precision    recall  f1-score   support

       <=50K       0.93      0.79      0.86     11360
        >50K       0.56      0.81      0.66      3700

    accuracy                           0.80     15060
   macro avg       0.74      0.80      0.76     15060
weighted avg       0.84      0.80      0.81     15060



In [464]:
rob1= RobustScaler()
x_trob = rob1.fit_transform(x_resampled)
x_testrob = rob1.transform(x_test)

In [465]:
gnb2= GaussianNB()

In [466]:
gnb2.fit(x_trob,y_resampled )
y_pred_rpb1 = gnb2.predict(x_testrob)

In [467]:
print(classification_report(y_test, y_pred_rpb1))

              precision    recall  f1-score   support

       <=50K       0.93      0.79      0.85     11360
        >50K       0.55      0.81      0.66      3700

    accuracy                           0.79     15060
   macro avg       0.74      0.80      0.75     15060
weighted avg       0.84      0.79      0.80     15060

